### ISSUE TITLE
Compilation error with Julia v1.0

### ISSUE THREAD

**Issue by kgori** [BioJulia/SubstitutionModels.jl#9]
The package currently does not compile with v1.0, due to a problem generating docstrings - see output below.

## Current Behavior
```
julia> using SubstitutionModels
[ Info: Precompiling SubstitutionModels [8365b1bb-bd83-58ee-a267-f2965fc81c73]
ERROR: LoadError: LoadError: LoadError: UndefVarError: @doc_str not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /Users/xxx/.julia/packages/SubstitutionModels/ySVC2/src/SubstitutionModels.jl:3
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:389
 [13] top-level scope at ./none:3
in expression starting at /Users/xxx/.julia/packages/SubstitutionModels/ySVC2/src/core.jl:7
in expression starting at /Users/xxx/.julia/packages/SubstitutionModels/ySVC2/src/core.jl:7
in expression starting at /Users/xxx/.julia/packages/SubstitutionModels/ySVC2/src/SubstitutionModels.jl:13
ERROR: Failed to precompile SubstitutionModels [8365b1bb-bd83-58ee-a267-f2965fc81c73] to /Users/xxx/.julia/compiled/v1.0/SubstitutionModels/28xme.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834
```

## Possible Solution / Implementation
Remove the word ```doc``` from docstrings in core.jl and nucleic_acids.jl

## Your Environment
- Package Version used: v0.1.0
- Julia Version used: v1.0
- Operating System and version (desktop or mobile): OSX

**Comment by jangevaare** [comment]
The master branch is working with Julia 1.0, I haven’t pushed a new release for it just yet however - I need to fix some LaTeX generation with documenter.jl after having made this change.

**Comment by jangevaare** [comment]
v0.2.0 is tagged now which provides Julia 0.7/1.0 support (awaiting merge to METADATA https://github.com/JuliaLang/METADATA.jl/pull/17801)
